version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - swm_strong
    networks:
      - backend

  redis:
    image: redis:7.2
    expose:
      - "6379"
    networks:
      - backend

  swm_strong:
    image: ${DOCKER_USERNAME}/swmstrong:latest
    container_name: swmstrong
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      MYSQL_URL: ${MYSQL_URL}
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MONGO_URL: ${MONGO_URL}
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - backend



networks:
  backend:
