version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  redis:
    image: redis:7.2
    ports:
      - "6379:6379"

  app:
    image: ${DOCKER_USERNAME}/swmstrong:latest
    container_name: swmstrong
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      MYSQL_URL: ${MYSQL_URL}
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MONGO_URL: ${MONGO_URL}
      REDIS_HOST: redis
      REDIS_PORT: 6379
